export default {
  HomeScreen: "HomeScreen",
  LoginScreen: "LoginScreen",
  SignUpScreen: "SignUpScreen",
  ForgotPasswordScreen: "ForgotPasswordScreen",
  SettingScreen: "SettingScreen",
  ChatWithAiScreen: "ChatWithAiScreen",
  AiPlanScreen: "AiPlanScreen",
  CreateClientScreen: "CreateClientScreen",
  ClientDetailScreen: "ClientDetailScreen",
  ProfileScreen: "ProfileScreen",
  NewTaskScreen: "NewTaskScreen",
  ChangePasswordScreen: "ChangePasswordScreen",
  AiSubscriptionScreen: "AiSubscriptionScreen",
  TodoAllTaskScreen: "TodoAllTaskScreen",
  TestingScreen: "TestingScreen",
  PageViewerScreen: "PageViewerScreen",
};
